name: Pull Request workflow

on:
    pull_request:
        branches: [ main ]

jobs:
  run-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout package
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install pytest
          python -m pytest tests/test_package.py
