name: Receiver for package update

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [ main ]

jobs:
  update-package:
    runs-on: ubuntu-latest
    # Disallow running on events triggered by a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout package
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Update package
        run: |
          echo -e "### Workflow dispatch testing receiver\n\n" $(date) > README.md
          git status
      - name: Create Pull Request
        # Only creates a new PR if there are changes
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CREATE_PR }}
          title: "[bot] Update README.md"
          # If workflow is running from `pull_request`
          # base: ${{ github.head_ref }}
          # If workflow is running from `release`
          # base: main
